### ISSUE TITLE
Highlight inline code

### ISSUE THREAD

**Issue by sbaack** [atom/one-light-syntax#13]
Thanks for this great theme. I write a lot in Markdown and noticed that inline code is not highlighted:

<img width="373" alt="screen shot 2015-09-24 at 8 55 20 pm" src="https://cloud.githubusercontent.com/assets/8274140/10083923/f86198b8-6300-11e5-8882-132d4a59847c.png">

It would be great if it could be highlighted, like this (using the [Writer syntax theme](https://atom.io/themes/writer-syntax) as an example):

<img width="373" alt="screen shot 2015-09-24 at 8 56 55 pm" src="https://cloud.githubusercontent.com/assets/8274140/10083950/16045a9a-6301-11e5-997d-cdd30a84e929.png">

**Comment by simurai** [comment]
Hmm.. Are you sure that the first screenshot is the `one-light-syntax` theme? I can't reproduce it. In my case inline code gets highlighted as greenish text:

![screen shot 2015-09-25 at 11 29 05 am](https://cloud.githubusercontent.com/assets/378023/10091660/2ba8fdce-6379-11e5-818a-614ee49232ea.png)

The Writer theme adds a background. That might be a good idea since in the rendered HTML output it usually also gets a `background`.

**Comment by simurai** [comment]
Ohh.. wait. I just realized that the green highlight got added a 15 days ago:https://github.com/atom/one-light-syntax/pull/11. So it hasn't been released to Atom stable yet.

@sbaack Are you ok with that change?

**Comment by sbaack** [comment]
That's great, thanks! Looking forward to the release :-) Will this also get fixed for the One-Dark and Base16 themes then?

**Comment by simurai** [comment]
One dark: Yes
Base16 themes: Just now, after you mentioned it. Thanks.

**Comment by sbaack** [comment]
You're welcome, and thank you again for fixing it. I guess this can be closed then.
