### ISSUE TITLE
Double click to select code.

### ISSUE THREAD

**Issue by Kole6** [atom/one-light-syntax#48]
I put forward the feeling of using it：

Double click to select code.

The background color of the same code is too shallow.

The same code has no hint on the right-hand sidebar.

**Comment by rsese** [comment]
Thanks for reaching out!

Please use the issue template as much as possible when opening issues, the information in the template is very helpful for us when triaging issues.

Can you share a screenshot of what you're describing?

Also, what version of Atom are you running (`atom -v`) and what operating system?

---

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by Kole6** [comment]
this
You can't comment at this time — your comment cannot be blank.

**Comment by Kole6** [comment]
https://upload-images.jianshu.io/upload_images/5141942-01ffa74ede6b46b9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240

**Comment by simurai** [comment]
@Kole6 Ohh.. I see. That is not supported by default, but you might can add it by installing https://atom.io/packages/minimap and maybe also https://atom.io/packages/minimap-highlight-selected.
